sudo: false

language: android
jdk: oraclejdk8

before_install:
  - bash .travis-android-license-bugfix.sh

android:
  components:
    - tools
    - platform-tools
    - tools

    - extra-android-support
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
- ./gradlew connectedCheck
- ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)