language: android

jdk: oraclejdk8

before_install:
  - bash .travis-android-license-bugfix.sh

android:
  components:
    - build-tools-23.0.1

before_install:
 - chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository